language: bash
sudo: required
services:
  - docker

  
env:
  matrix:
    - HUGO_VERSION=0.20.2

    - PHP_VERSION=5.6 BUILD_SERVICE=workspace
    - PHP_VERSION=7.0 BUILD_SERVICE=workspace
    - PHP_VERSION=7.1 BUILD_SERVICE=workspace
    - PHP_VERSION=7.2 BUILD_SERVICE=workspace
    - PHP_VERSION=7.3 BUILD_SERVICE=workspace
    - PHP_VERSION=7.4 BUILD_SERVICE=workspace

    - PHP_VERSION=5.6 BUILD_SERVICE=php-fpm
    - PHP_VERSION=7.0 BUILD_SERVICE=php-fpm
    - PHP_VERSION=7.1 BUILD_SERVICE=php-fpm
    - PHP_VERSION=7.2 BUILD_SERVICE=php-fpm
    - PHP_VERSION=7.3 BUILD_SERVICE=php-fpm
    - PHP_VERSION=7.4 BUILD_SERVICE=php-fpm

    - PHP_VERSION=hhvm BUILD_SERVICE=hhvm

    # - PHP_VERSION=5.6 BUILD_SERVICE=php-worker
    - PHP_VERSION=7.0 BUILD_SERVICE=php-worker
    - PHP_VERSION=7.1 BUILD_SERVICE=php-worker
    - PHP_VERSION=7.2 BUILD_SERVICE=php-worker
    - PHP_VERSION=7.3 BUILD_SERVICE=php-worker
    - PHP_VERSION=7.4 BUILD_SERVICE=php-worker

    - PHP_VERSION=7.0 BUILD_SERVICE=laravel-horizon
    - PHP_VERSION=7.1 BUILD_SERVICE=laravel-horizon
    - PHP_VERSION=7.2 BUILD_SERVICE=laravel-horizon
    - PHP_VERSION=7.3 BUILD_SERVICE=laravel-horizon
    - PHP_VERSION=7.4 BUILD_SERVICE=laravel-horizon

    - PHP_VERSION=NA BUILD_SERVICE=solr
    - PHP_VERSION=NA BUILD_SERVICE="mssql rethinkdb aerospike"
    - PHP_VERSION=NA BUILD_SERVICE="blackfire minio percona nginx caddy apache2 mysql mariadb postgres postgres-postgis neo4j mongo redis cassandra"
    - PHP_VERSION=NA BUILD_SERVICE="adminer phpmyadmin pgadmin"
    - PHP_VERSION=NA BUILD_SERVICE="memcached beanstalkd beanstalkd-console rabbitmq elasticsearch certbot mailhog maildev selenium jenkins proxy proxy2 haproxy gearman"
    - PHP_VERSION=NA BUILD_SERVICE="kibana grafana laravel-echo-server"
    - PHP_VERSION=NA BUILD_SERVICE="ipython-controller manticore"
    # - PHP_VERSION=NA BUILD_SERVICE="aws"



# Before
before_install:
  - docker version
install:
  #- docker-compose up -d nginx mysql workspace
  - sudo docker run hello-world

  

